version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka_ui:
    image: docker.io/provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "3000:3000"

  # user-service:
  #   build: ./user-service
  #   ports:
  #     - "3001:3001"

  # pos-service:
  #   build: ./pos-service
  #   ports:
  #     - "3002:3002"

  # accounting-service:
  #   build: ./accounting-service
  #   ports:
  #     - "3003:3003"

  # notification-service:
  #   build: ./notification-service
